# Generated by Django 4.1.5 on 2023-02-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="week_number",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
